steps:
  # Step 0: Install dependencies and run tests
  - name: 'node'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        yarn 
        yarn test
  
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR) or Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - nestjs-app
      - --image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated # Adjust based on your app's access needs

# Substitutions for build
substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: nodejs-number
# Timeout settings (optional)
timeout: '1890s'

# Artifacts (optional, for debugging or logs)
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-artifacts/'
    paths: ['**/*.log']
