options:
  logging: CLOUD_LOGGING_ONLY


steps:
   # Step 0: Install dependencies and run tests
  - name: gcr.io/cloud-builders/gcloud
    id: 'load-env'
    entrypoint: sh
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=$_SERVICE_NAME-staging --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env
        cat .env

  
  # Step 1: Install dependencies and run tests
  - name: 'node'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        yarn 
        yarn test
  
  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']

  # Step 3: Push the Docker image to Google Container Registry (GCR) or Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated # Adjust based on your app's access needs

# Substitutions for build
substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: nodejs-number

timeout: '1890s'
